name: jpsvis-unix

on: [pull_request, push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:21.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y software-properties-common
          apt-get update && apt-get install -y wget \
                                 git \
                                 g++ \
                                 clang-12 \
                                 cmake \
                                 ninja-build \
                                 libglu1-mesa-dev \
                                 freeglut3-dev \
                                 mesa-common-dev \
                                 libvtk9-dev \
                                 libvtk9-qt-dev \
                                 qtbase5-dev \
                                 libglm-dev

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose
